project_id = "alzsygiawculzaeygzoj"

[functions.process-idea]
verify_jwt = false

[functions.brainstorm-chat]
verify_jwt = false

[functions.fetch-link-preview]
verify_jwt = false

[functions.generate-strategy]
verify_jwt = false

[functions.project-chat]
verify_jwt = false

[functions.campaign-chat]
verify_jwt = false
